### ISSUE TITLE
Trigger "shelteralarm" unknown

### ISSUE THREAD

**Issue by giu889** [CornerBit/HikSink#1]
For some of my cameras the tamper alarm does not work and I get the following error. [PyHik seems to have had the same issue in the past.](https://github.com/mezz64/pyHik/issues/43)

```
Oct 02 09:40:47.673  WARN hik_sink::mqtt::manager: Camera send an alert for a trigger which does not exist camera="kamera_vorgarten_rechts" trigger=Unknown("shelteralarm")
```

And by the way, thank you for creating HikSink. It's working so much better than the native Home Assistant integration.

**Comment by CornerBit** [comment]
Thanks for finding the relevant PyHik issue!  I've made `shelteralarm` link with tamper detection. This is now in version 1.1.0 which you can pull from docker.
