### ISSUE TITLE
ColorVue cameras not working

### ISSUE THREAD

**Issue by iondarie** [CornerBit/HikSink#10]
Hello,

I am trying to use HikSink to connect to my ColorVue cameras but unfortunately all i get is:

``2022-09-16T18:17:35.196276Z ERROR Camera coms{camera=Intrare id=intrare}: hik_sink::hikapi::camera: Error reconnecting to camera Could not authenticate with camera: Invalid status code after auth token sent: 500``

|date|stream|content|
|----|------|-------|
|2022-09-16T18:18:02.547409286Z|stdout|[2m2022-09-16T18:18:02.547096Z[0m [34mDEBUG[0m [1mCamera coms[0m[1m{[0m[3mcamera[0m[2m=[0mIntrare [3mid[0m[2m=[0mintrare[1m}[0m[2m:[0m [2mhyper::client::connect::http[0m[2m:[0m connecting to 192.168.1.81:65001|
|2022-09-16T18:18:02.548749550Z|stdout|[2m2022-09-16T18:18:02.548630Z[0m [34mDEBUG[0m [1mCamera coms[0m[1m{[0m[3mcamera[0m[2m=[0mIntrare [3mid[0m[2m=[0mintrare[1m}[0m[2m:[0m [2mhyper::client::connect::http[0m[2m:[0m connected to 192.168.1.81:65001|
|2022-09-16T18:18:02.548863301Z|stdout|[2m2022-09-16T18:18:02.548767Z[0m [34mDEBUG[0m [2mhyper::proto::h1::io[0m[2m:[0m flushed 80 bytes|
|2022-09-16T18:18:02.553114121Z|stdout|[2m2022-09-16T18:18:02.553013Z[0m [34mDEBUG[0m [2mhyper::proto::h1::io[0m[2m:[0m parsed 7 headers|
|2022-09-16T18:18:02.553172289Z|stdout|[2m2022-09-16T18:18:02.553024Z[0m [34mDEBUG[0m [2mhyper::proto::h1::conn[0m[2m:[0m incoming body is content-length (178 bytes)|
|2022-09-16T18:18:02.553217345Z|stdout|[2m2022-09-16T18:18:02.553042Z[0m [34mDEBUG[0m [2mhyper::proto::h1::conn[0m[2m:[0m incoming body completed|
|2022-09-16T18:18:02.553268169Z|stdout|[2m2022-09-16T18:18:02.553186Z[0m [34mDEBUG[0m [1mCamera coms[0m[1m{[0m[3mcamera[0m[2m=[0mIntrare [3mid[0m[2m=[0mintrare[1m}[0m[2m:[0m [2mhyper::client::connect::http[0m[2m:[0m connecting to 192.168.1.81:65001|
|2022-09-16T18:18:02.554563468Z|stdout|[2m2022-09-16T18:18:02.554474Z[0m [34mDEBUG[0m [1mCamera coms[0m[1m{[0m[3mcamera[0m[2m=[0mIntrare [3mid[0m[2m=[0mintrare[1m}[0m[2m:[0m [2mhyper::client::connect::http[0m[2m:[0m connected to 192.168.1.81:65001|
|2022-09-16T18:18:02.554623255Z|stdout|[2m2022-09-16T18:18:02.554550Z[0m [34mDEBUG[0m [2mhyper::proto::h1::io[0m[2m:[0m flushed 374 bytes|
|2022-09-16T18:18:02.562266490Z|stdout|[2m2022-09-16T18:18:02.561980Z[0m [34mDEBUG[0m [2mhyper::proto::h1::io[0m[2m:[0m parsed 7 headers|
|2022-09-16T18:18:02.562454807Z|stdout|[2m2022-09-16T18:18:02.562037Z[0m [34mDEBUG[0m [2mhyper::proto::h1::conn[0m[2m:[0m incoming body is content-length (1136 bytes)|
|2022-09-16T18:18:02.562503386Z|stdout|[2m2022-09-16T18:18:02.562052Z[0m [34mDEBUG[0m [2mhyper::proto::h1::conn[0m[2m:[0m incoming body completed|
|2022-09-16T18:18:02.562561834Z|stdout|[2m2022-09-16T18:18:02.562411Z[0m [34mDEBUG[0m [1mCamera coms[0m[1m{[0m[3mcamera[0m[2m=[0mIntrare [3mid[0m[2m=[0mintrare[1m}[0m[2m:[0m [2mhyper::client::connect::http[0m[2m:[0m connecting to 192.168.1.81:65001|
|2022-09-16T18:18:02.563823710Z|stdout|[2m2022-09-16T18:18:02.563745Z[0m [34mDEBUG[0m [1mCamera coms[0m[1m{[0m[3mcamera[0m[2m=[0mIntrare [3mid[0m[2m=[0mintrare[1m}[0m[2m:[0m [2mhyper::client::connect::http[0m[2m:[0m connected to 192.168.1.81:65001|
|2022-09-16T18:18:02.563911155Z|stdout|[2m2022-09-16T18:18:02.563828Z[0m [34mDEBUG[0m [2mhyper::proto::h1::io[0m[2m:[0m flushed 77 bytes|
|2022-09-16T18:18:02.568210240Z|stdout|[2m2022-09-16T18:18:02.568039Z[0m [34mDEBUG[0m [2mhyper::proto::h1::io[0m[2m:[0m parsed 7 headers|
|2022-09-16T18:18:02.568454077Z|stdout|[2m2022-09-16T18:18:02.568070Z[0m [34mDEBUG[0m [2mhyper::proto::h1::conn[0m[2m:[0m incoming body is content-length (178 bytes)|
|2022-09-16T18:18:02.568528318Z|stdout|[2m2022-09-16T18:18:02.568086Z[0m [34mDEBUG[0m [2mhyper::proto::h1::conn[0m[2m:[0m incoming body completed|
|2022-09-16T18:18:02.568567893Z|stdout|[2m2022-09-16T18:18:02.568264Z[0m [34mDEBUG[0m [1mCamera coms[0m[1m{[0m[3mcamera[0m[2m=[0mIntrare [3mid[0m[2m=[0mintrare[1m}[0m[2m:[0m [2mhyper::client::connect::http[0m[2m:[0m connecting to 192.168.1.81:65001|
|2022-09-16T18:18:02.569325423Z|stdout|[2m2022-09-16T18:18:02.569235Z[0m [34mDEBUG[0m [1mCamera coms[0m[1m{[0m[3mcamera[0m[2m=[0mIntrare [3mid[0m[2m=[0mintrare[1m}[0m[2m:[0m [2mhyper::client::connect::http[0m[2m:[0m connected to 192.168.1.81:65001|
|2022-09-16T18:18:02.569384804Z|stdout|[2m2022-09-16T18:18:02.569322Z[0m [34mDEBUG[0m [2mhyper::proto::h1::io[0m[2m:[0m flushed 368 bytes|
|2022-09-16T18:18:02.591458805Z|stdout|[2m2022-09-16T18:18:02.591251Z[0m [34mDEBUG[0m [2mhyper::proto::h1::io[0m[2m:[0m parsed 7 headers|
|2022-09-16T18:18:02.591633774Z|stdout|[2m2022-09-16T18:18:02.591282Z[0m [34mDEBUG[0m [2mhyper::proto::h1::conn[0m[2m:[0m incoming body is content-length (275 bytes)|
|2022-09-16T18:18:02.591689834Z|stdout|[2m2022-09-16T18:18:02.591297Z[0m [34mDEBUG[0m [2mhyper::proto::h1::conn[0m[2m:[0m incoming body completed|
|2022-09-16T18:18:02.591789257Z|stdout|[2m2022-09-16T18:18:02.591478Z[0m [31mERROR[0m [1mCamera coms[0m[1m{[0m[3mcamera[0m[2m=[0mIntrare [3mid[0m[2m=[0mintrare[1m}[0m[2m:[0m [2mhik_sink::hikapi::camera[0m[2m:[0m Error reconnecting to camera Could not authenticate with camera: Invalid status code after auth token sent: 500|
|2022-09-16T18:18:02.591876875Z|stdout|[2m2022-09-16T18:18:02.591531Z[0m [34mDEBUG[0m [2mhik_sink::mqtt::connection[0m[2m:[0m Camera event [3mid[0m[2m=[0m"intrare" [3mevent[0m[2m=[0mDisconnected { error: "Reconnection failure: Could not authenticate with camera: Invalid status code after auth token sent: 500" }|

This is my config:

```[system]
# Supports TRACE, DEBUG, INFO, WARN, and ERROR
log_level = "DEBUG"

[mqtt]
address = "192.168.1.99"
port = 1883
username = "mosquitto"
password = "*****"
# Optional: Customise the client ID used when connecting to the MQTT broker
# client_id = "hik-sink"
# The MQTT topic under which all camera events will be published
base_topic = "hikvision_cameras"
home_assistant_topic = "homeassistant"

# Duplicate this camera section to add multiple cameras
[[camera]]
name = "Intrare"
address = "192.168.1.81"
# Port is optional. Use this if your camera is behind an NVR.
port = 65001 //port of the IP camera assigned by the NVR
# The username and password of any account that has 'Notify Surveillance Center' permissions.
username = "admin"
password = "*****"
```

Am i doing something wrong?

**Comment by CornerBit** [comment]
Did you manage to solve this with a firmware update? Curious so I can keep track of which cameras are shipping with bad FW.
