### ISSUE TITLE
Newbie questions

### ISSUE THREAD

**Issue by daveo2k** [CornerBit/HikSink#12]
I'll start by saying i'm a newbie to Docker, i've got Hik-Sink working now with multiple cameras.
Question though at the moment i keep having to remove the container to reconfigure...is there an easier way?  I did try the cp cmd into the container but it didn't like it...like i say i'm a newbie to docker so 100% i'm probably doing it wrong!

Great app though! 
Dave

**Comment by daveo2k** [comment]
Hee's what i've tried for multiple cameras but Hik-Sink just seems to be picking up and connecting to the second camera.

# Duplicate this camera section to add multiple cameras
[[camera]]
name = "Front Drive"
address = "192.168.69.37"
# Port is optional. Use this if your camera is behind an NVR.
port = 837
# The username and password of any account that has 'Notify Surveillance Center' permissions.
username = "username"
password = "password"

name = "West Drive"
address = "192.168.69.40"
# Port is optional. Use this if your camera is behind an NVR.
port = 840
# The username and password of any account that has 'Notify Surveillance Center' permissions.
username = "username"
password = "password"

**Comment by CornerBit** [comment]
Yeah its a little counterintuitive, but removing the container and recreating is a standard approach to containerised systems. In this case however, you can get by with just restarting the container when you change the config as HikSink reads in the config on boot. Feel free to reopen the issue if you've got any other queries.
