### ISSUE TITLE
Have Hik-Sink start on boot

### ISSUE THREAD

**Issue by daveo2k** [CornerBit/HikSink#13]
I'm running Hik-Sink standalone on a Raspberry Pi, is there anyway to have the app start on boot?  I've got this working at the moment via bashrc but then if you ssh in to the Pi the app launches when the Pi is logged in to via SSH and i just hang the session so the app continues to run.  Be good if it could be done via systemd or similar?

**Comment by pentafive** [comment]
@daveo2k, If you still have this issue try adding it to the /etc/rc.local file. 

More info here: [https://raspberrypi-guide.github.io/programming/run-script-on-boot](url)

**Comment by CornerBit** [comment]
Ideally you would use systemd and turn HikSink into a service. There are a few tutorials around online about how to do this, e.g. https://medium.com/@benmorel/creating-a-linux-service-with-systemd-611b5c8b91d6
