### ISSUE TITLE
Support to set MQTT ClientId

### ISSUE THREAD

**Issue by Zolli** [CornerBit/HikSink#2]
Hello, thanks for this good software, it seems awesome work. I would like to request a small new feature. Mz MQTT broker requires a specific clientId for each user but looks like this client use a random clientId on ecah connection attemp. Looks like the used MQTT library support provided clientId. Thanks

**Comment by CornerBit** [comment]
Thanks for the suggestion! I've added support for custom client IDs in version 1.2.0. You can pull this update from docker with:

```bash
docker pull cornerbit/hiksink:1.2.0
```

**Comment by Zolli** [comment]
Wow, awesome work, thanks for that. I try it tomorrow.
