### ISSUE TITLE
Catch backtrace

### ISSUE THREAD

**Issue by fabaff** [CornerBit/HikSink#3]
Running without flags or options defined leads to an error that is not caught.

```bash
$ ./bin/hik_sink 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "missing field `system`"', src/main.rs:30:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by CornerBit** [comment]
The error thrown is indicative of an invalid or missing configuration file. Can you check if the `config.toml` is in your current working directory? I agree that the error is a bit cryptic. I'll push out something prettier in the next release.

**Comment by CornerBit** [comment]
Closing as I believe this is resolved in the last releases.
