### ISSUE TITLE
Does not work with DS-2CD2T46G2-ISU.

### ISSUE THREAD

**Issue by mikelis-urlovskis** [CornerBit/HikSink#5]
Does not work with DS-2CD2T46G2-ISU / SL (AcuSense) camera, works fine with other cameras.
Error:  hik_sink::hikapi::camera: Error reconnecting to camera Could not authenticate with camera: Invalid status code after auth token sent: 500

**Comment by CornerBit** [comment]
That seems to be an issue with the camera's server software - error 500 means internal error. Could you check if your camera is on the latest firmware? I've seen a couple of occasions now where FW updates have silently fixed these types of API issues...

**Comment by mikelis-urlovskis** [comment]
Works after update. It was quit hard to update camers so many failed to update errors.
