### ISSUE TITLE
Intercom

### ISSUE THREAD

**Issue by MuadDibVV** [CornerBit/HikSink#6]
Hello,
Thanks for your beautiful work.
Is it possible to manage intercom like DS-KV6113 ?

Here you can find any information and my method to get call status

[intercom.pdf](https://github.com/CornerBit/HikSink/files/8090752/intercom.pdf)

**Comment by CornerBit** [comment]
Unfortunately it looks like call status is not delivered over the normal event stream. I don't own an intercom, but I've been weighing up getting one. If I do, I'll add it in.
