### ISSUE TITLE
Anyway to make this work as HA addons instead?

### ISSUE THREAD

**Issue by Buster14** [CornerBit/HikSink#7]
Would rather not install docker or MQTT since, i'm running HA on vmware workstation windows,
and secondly it would probably involve more handshake process isnt it?

**Comment by Buster14** [comment]
Ok i noticed this can be compiled with rust, so is it possible to make a standalone exe through that? Sorry i'm not familiar with rust

**Comment by CornerBit** [comment]
Unfortunately its all pretty tied to MQTT at the moment, and would require a bit of work to move over to HA. If there was a HA rust library I'd consider adding it in, but AFAIK this doesn't exist. You can run this in windows, as I have done during development, but that would still require getting access to an MQTT server.
